# Generated by Django 4.1.3 on 2023-05-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
    ]
